### PR TITLE
Pimcore 11 compatibility fixes

### PR DESCRIPTION
**Pull request by GNi33**
This PR adds a few compatibility fixes for Pimcore 11.

For example, the PaymentProviderInstaller implementation of Pimcore 11 added typed properties, which this bundle does not have until now, causing exceptions when installing the bundle. Also, the way the bearer authorization is implemented does not work with the version of GuzzleHttp that Pimcore 11 uses.

### CODE REVIEW

**Comment by markus-moser** [comment]
Thx a lot - I merge it into #8 to see if PHPStan runs through

**Comment by markus-moser** [comment]
@GNi33 It's now merged into the 2.x branch. Unfortunately it's impossible for me to test if it really works, so please let me know if you had the chance to test the 2.x branch. If it works I can release a 2.0 version.

**Comment by GNi33** [comment]
@markus-moser works fine so far for us in production as well as testSystem mode. We will continue to monitor it, but the basic use case of payment via the CopyAndPay API is looking good so far.

**Comment by markus-moser** [comment]
@GNi33 Thanks a lot for your feedback, I released v2 now based on your work 👍

**Pull request merged**
